<a href="https://colab.research.google.com/github/pranathi1615/PDS-1615/blob/main/lab(22-8).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
fp=open("example.txt","w")
fp.write("Hello,B.Tech students!\n")
fp.write("sR university")
fp.write("suresh kumar")

12

In [10]:
fp.write("Hello btech students!\n")
fp.write("This is file handling in python.\n")
fp.write("Sr University")
fp.write("sateesh kumar")
fp.close()
print("file written sucessfully")


file written sucessfully


In [8]:
#Reading from a file
#open file in read mode
file=open("example.txt","r")
#read entire content
content=file.read()
print("file content:\n",content)
#close file
file.close()
#read line by line
file=open("example.txt","r")
line1=file.readline()
print("firstline:",line1)
line2=file.readline()
print("secondline:",line2)
line3=file.readline()
print("Line:",line3)
file.close()

file content:
 Hello,B.Tech students!
sR universitysuresh kumarHello btech students!
This is file handling in python.
Sr Universitysateesh kumarAppending new data...

firstline: Hello,B.Tech students!

secondline: sR universitysuresh kumarHello btech students!

Line: This is file handling in python.



In [5]:
file=open("example.txt","r")
lines=file.readlines()
print("All lines as list:",lines)
file.close()

All lines as list: ['Hello,B.Tech students!\n', 'sR universitysuresh kumarHello btech students!\n', 'This is file handling in python.\n', 'Sr Universitysateesh kumar']


In [7]:
#appending data to an exisitoing file
file=open("example.txt","a")
file.write("Appending new data...\n")
file.close()


In [11]:
#using with statement
with open("example.txt","r") as fp:
  data=fp.read()
  print(data)

Hello,B.Tech students!
sR universitysuresh kumarHello btech students!
This is file handling in python.
Sr Universitysateesh kumar


In [20]:
#workin g with csv files
import csv
with open("data.csv","w",newline='')as fp:
  wr=csv.writer(fp)
  wr.writerows([["Name","age","course"],["aaa",21,"CSE"],["bbb",20,"ECE"]])
  #reading with csv
with open("data.csv","r")as file:
    re= csv.reader(file)
    for row in re:
      print(row)


['Name', 'age', 'course']
['aaa', '21', 'CSE']
['bbb', '20', 'ECE']


In [29]:
import numpy as np
#1D Array
arr1=np.array([1,2,3,4])
print(arr1)
#2D Array
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)
#zero arrays
z_arr=np.zeros((3,3))
print(z_arr)
#ones array
ones_arr=np.ones((2,4))
print(ones_arr)
#range of numbers
range_arr=np.arange(0,10,2)
print(range_arr)
rand_arr=np.random.rand(2,3)
print(rand_arr)


[1 2 3 4]
[[1 2 3]
 [4 5 6]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[0 2 4 6 8]
[[0.6030899  0.88952492 0.23836314]
 [0.16393423 0.57894267 0.37118673]]


In [32]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.shape)
print(arr.ndim)
print(arr.dtype)
print(arr.size)
print(arr.itemsize)

(2, 3)
2
int64
6
8


In [35]:
a=np.array([10,20,30,40,50])
print("first element:",a[0])
print("last element:",a[-1])
print("slice[1:4]:",a[1:4])
print("every second element:",a[::2])
#2D indexing
arr2=np.array([[1,2,3],[4,5,6]])
print("element at r1 col 2:",arr2[0,1])
print("second row",arr2[1,:])
print("second column:",arr2[:,1])

first element: 10
last element: 50
slice[1:4]: [20 30 40]
every second element: [10 30 50]
element at r1 col 2: 2
second row [4 5 6]
second column: [2 5]
